#port
server:
  port: 8080
#Jwe secret
tim:
  jwtExpirationMs: 86400000
  jwtRefreshExpirationMs: 2592000000
  jwtSecret: mySecretKey
  
# Logging
logging:
  file: 
    name: logs/app.log
  level:
    root: INFO
    com:
      tim: DEBUG
    org:
      springframework: WARN
  pattern:
    console: '%d{yy-MM-dd E HH:mm:ss.SSS} %clr(%-5p ${PID} --- [%8.15t]) %clr(%-40.40logger{0}){blue} %clr(:){red} %m%n'
    file: '%d %-5p ${PID} --- [%8.15t] %-40.40logger{0} : %m%n'
  
#Spring Jpa
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  web:
    resources.static-locations: classpath:/upload/,file:excel/, file:upload/
#config swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#fileSize
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB